# Generated by Django 4.2.9 on 2024-01-23 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boletos_disponibles', models.PositiveIntegerField()),
                ('artista_concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts_app.artista')),
                ('ubicacion_concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts_app.ubicacion')),
            ],
        ),
    ]
