# Generated by Django 4.2.11 on 2024-04-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivales_app', '0003_parking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='artistas')),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('escenario', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField()),
                ('boletos_disponibles', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='conciertos')),
                ('artista_concierto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts_app.artista')),
                ('festival_concierto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciertos', to='festivales_app.festival')),
            ],
        ),
    ]
