# Generated by Django 4.2.11 on 2024-04-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concierto',
            name='boletos_disponibles',
        ),
    ]
