# Generated by Django 4.2.11 on 2024-05-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0002_remove_concierto_boletos_disponibles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concierto',
            old_name='festival_concierto',
            new_name='festival_relacionado',
        ),
    ]
