# Generated by Django 4.2.9 on 2024-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0004_alter_notificacion_options_alter_ubicacion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='artistas'),
        ),
    ]
