# Generated by Django 4.2.11 on 2024-05-05 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0006_alter_concierto_artista_concierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='concierto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts_app.concierto'),
        ),
    ]
