# Generated by Django 4.2.9 on 2024-02-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0006_concierto_descripcion_concierto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='boletos_disponibles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
