# Generated by Django 4.2.11 on 2024-05-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0007_alter_artista_concierto_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='artista_concierto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts_app.artista'),
        ),
    ]
