# Generated by Django 4.2.9 on 2024-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0007_alter_concierto_boletos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='boletos_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
