# Generated by Django 4.2.9 on 2024-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0008_alter_concierto_boletos_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierto',
            name='valoracion_media',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
