# Generated by Django 5.0.6 on 2024-05-23 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0008_alter_concierto_artista_concierto'),
        ('festivales_app', '0008_alter_festival_precio_entrada_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='festival_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciertos', to='festivales_app.festival'),
        ),
    ]
