# Generated by Django 4.2.13 on 2024-06-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0009_alter_concierto_festival_relacionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='concierto_relacionado',
        ),
    ]
