# Generated by Django 4.2.9 on 2024-02-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0010_alter_concierto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='artista_concierto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concerts_app.artista'),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
