# Generated by Django 4.2.13 on 2024-06-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0011_rename_nombre_concierto_nombre_concierto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concierto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='concierto',
            name='escenario',
        ),
        migrations.RemoveField(
            model_name='concierto',
            name='foto',
        ),
    ]
