# Generated by Django 4.2.9 on 2024-02-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts_app', '0012_alter_concierto_artista_concierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='foto',
            field=models.ImageField(upload_to='conciertos'),
        ),
    ]
