# Generated by Django 4.2.9 on 2024-02-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('concerts_app', '0014_alter_artista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='cliente_notificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.cliente'),
        ),
    ]
