# Generated by Django 4.2.11 on 2024-04-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('boletos_disponibles', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='festivales')),
                ('valoracion_media', models.FloatField(blank=True, default=None, null=True)),
                ('disponibilidad_autobuses', models.BooleanField(default=False)),
                ('disponibilidad_parking', models.BooleanField(default=False)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('genero_principal', models.CharField(max_length=100)),
                ('ubicacion_festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivales_app.ubicacion')),
            ],
            options={
                'verbose_name_plural': 'Festivales',
            },
        ),
    ]
