# Generated by Django 4.2.11 on 2024-04-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_parada', models.CharField(max_length=255)),
                ('capacidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_salida', models.DateTimeField()),
                ('festival_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivales_app.festival')),
            ],
        ),
    ]
