# Generated by Django 4.2.11 on 2024-04-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name_plural': 'Festivales'},
        ),
    ]
