# Generated by Django 4.2.11 on 2024-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0002_alter_festival_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
