# Generated by Django 4.2.11 on 2024-04-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0003_alter_festival_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='fecha',
            field=models.DateField(),
        ),
    ]
