# Generated by Django 5.0.6 on 2024-05-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0005_autobus_plazas_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='entradas_general',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='entradas_oro',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='entradas_platino',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
