# Generated by Django 5.0.6 on 2024-05-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0006_festival_entradas_general_festival_entradas_oro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='precio_entrada_general',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='precio_entrada_oro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='precio_entrada_platino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
