# Generated by Django 5.0.6 on 2024-05-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivales_app', '0009_alter_festival_entradas_general_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='precio_entrada',
        ),
    ]
