# Generated by Django 4.2.11 on 2024-05-01 15:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('festivales_app', '0004_alter_autobus_options_alter_parking_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaFestival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('festival_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivales_app.festival')),
            ],
            options={
                'verbose_name_plural': 'Reservas de Festivales',
            },
        ),
        migrations.CreateModel(
            name='ReservaAutobus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autobus_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivales_app.autobus')),
                ('cliente_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservas de Autobuses',
            },
        ),
    ]
