# Generated by Django 4.2.11 on 2024-05-05 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivales_app', '0005_autobus_plazas_disponibles_and_more'),
        ('tickets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_tickets', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parking_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivales_app.parking')),
            ],
            options={
                'verbose_name_plural': 'Reservas de Parkings',
            },
        ),
    ]
