# Generated by Django 4.2.9 on 2024-01-23 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concerts_app', '0001_initial'),
        ('tickets_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cliente_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='concierto_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concerts_app.concierto'),
        ),
    ]
