# Generated by Django 4.2.9 on 2024-01-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='total',
            new_name='importe',
        ),
    ]
