# Generated by Django 4.2.9 on 2024-02-08 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets_app', '0003_rename_total_reserva_importe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('reserva_valoracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tickets_app.reserva')),
                ('usuario_valoracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='valoracion_usuario',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets_app.valoracion'),
        ),
    ]
