# Generated by Django 4.2.9 on 2024-02-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0004_valoracion_reserva_valoracion_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name_plural': 'Valoraciones'},
        ),
    ]
